//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter.ConverterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConverterServiceReference.IConverterService")]
    public interface IConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/GetData", ReplyAction="http://tempuri.org/IConverterService/GetDataResponse")]
        string GetData(string currencyAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/GetData", ReplyAction="http://tempuri.org/IConverterService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string currencyAmount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConverterServiceChannel : CurrencyConverter.ConverterServiceReference.IConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterServiceClient : System.ServiceModel.ClientBase<CurrencyConverter.ConverterServiceReference.IConverterService>, CurrencyConverter.ConverterServiceReference.IConverterService {
        
        public ConverterServiceClient() {
        }
        
        public ConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string currencyAmount) {
            return base.Channel.GetData(currencyAmount);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string currencyAmount) {
            return base.Channel.GetDataAsync(currencyAmount);
        }
    }
}
